name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: count program lines
        run: |
            totalFilesLines=0
            shopt -s globstar
            for file in ./**
            do
                if [ -d $file ];then
                  continue
                fi
                if [[ "$file" == */generated/* ]]; then
                  continue
                fi
                if [[ "$file" == *.jar ]]; then
                  continue
                fi
                fileLines=`grep -c '' $file`
                echo "fileName = $file"
                echo "linesCount = $fileLines"
                let totalFilesLines=$fileLines+$totalFilesLines
            done
            echo "totalFilesLines = $totalFilesLines"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: | 
          if ! dotnet test --no-restore --verbosity normal; then
            echo "搜索 [FAIL] 关键字 检索到的行 即是错误的test 这些test导致了本步骤出错. 需要检查对应的报错处 以修复错误"
            echo "此处的关键词搜索应在右上角的 搜索框 中执行 [注意 ctrl + F 会检索不到]"
            exit 1
          fi
